application: nethacknomictools
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.application

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- scores\.xlogfile
